### PR TITLE
fix vulnerabilities

### PR DESCRIPTION
**Pull request by arrlancore**
Update codecovio at #18
npm audit

### CODE REVIEW

**Comment by ikhsanalatsary** [comment]
@arrlancore are you able to resolve this conflict?

**Comment by arrlancore** [comment]
Sure, will fix asap

> @arrlancore are you able to resolve this conflict?

**Comment by ikhsanalatsary** [comment]
thanks @arrlancore ⭐️

**Comment by ikhsanalatsary** [comment]
@arrlancore sorry, I must revert this pull request because you deleted `index.d.ts`

**Pull request merged**
